project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

editor: source
execute:
  freeze: auto
filters:
  - nceas-learning-hub/theme
exercises: ### for custom theme callouts
  number: true ### see https://cambiotraining.github.io/quarto-course-template/materials/02-content_guidelines.html

website:
  title: "NCEAS Training Series: Supporting Effective Collaboration in Working Groups"
  repo-url: https://github.com/nceas-learning-hub/nceas-wg-portal
  repo-actions: [issue]
  favicon: images/logo_lh.png
  bread-crumbs: false
  navbar:
    right:
      - icon: github
        href: https://github.com/nceas-learning-hub/nceas-wg-portal
        aria-label: GitHub
  sidebar:
    title: "Materials"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: nceas-learning-hub.github.io/nceas-wg-portal
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
    contents:
      - text: "Series Home"
        href: index.qmd
      - section: "{{< fa brands github >}} Git & GitHub"
        contents:
        - text: "Setup"
          href: git-github-01_setup.qmd
        - text: "Fundamentals"
          href: git-github-02_fundamentals.qmd
        - text: "Resolving Conflicts"
          href: git-github-03_conflict.qmd
        - text: "Advanced Features"
          href: git-github-04_advanced.qmd
        - text: "Project Management"
          href: git-github-05_project-mgmt.qmd
        - text: "**_Recordings_**"
          href: recordings/git-github.qmd
      - section: "{{< fa screwdriver-wrench >}} Data Science"
        contents:
        - text: "Data Management & Reproducibility"
          href: data-sci_reproducibility.qmd
        - text: "Parallel Computing in R"
          href: data-sci_parallel-computing.qmd
        - text: "**_Recordings_**"
          href: recordings/data-sci.qmd
      - section: "{{< fa people-group >}} Team Science"
        contents:
        - text: "Successful Facilitation"
          href: team-sci_facilitation.qmd
        - text: "Communication Plans"
          href: team-sci_communication-plan.qmd
        - text: "Communicating Results"
          href: team-sci_communicate-external.qmd
        - text: "**_Recordings_**"
          href: recordings/team-sci.qmd
      - section: "{{< fa brush >}} Graphic Design"
        contents:
        - text: "With Canva"
          href: design_canva-basics.qmd
        - text: With GoogleDocs
          href: design_googledocs.qmd
        - text: "**_Recordings_**"
          href: recordings/design.qmd
      - text: "Other NCEAS Resources"
        href: nceas-resources.qmd
  page-footer:
    center: "Copyright &copy; 2026, [NCEAS](https://www.nceas.ucsb.edu/) | [{{< fa scale-balanced >}} CC 4.0 International](http://creativecommons.org/licenses/by/4.0/) "

format:
  theme-html
