---
title: About the course
format:
  theme-html:
    toc: false
---

::: column-margin

:::


## NCEAS Training Series: Supporting Effective Collaboration in Working Groups

Welcome to the **NCEAS Working Group Training Series**, specially designed to help working groups collaborate more effectively throughout every stage of their research process. These trainings cover essential collaboration strategies and practical skills, from facilitation and communication to data management and version control.

This training series is designed to foster both individual development and effective team collaboration. Training topics offers practical guidance on group facilitation, strategies for clear and productive communication, and hands-on skills for managing data and projects in a collaborative environment. Whether you're getting ready for your first group meeting or fine-tuning established workflows, these trainings offer valuable tools to support your success.

### How to Participate

We encourage each team to:

1. **Review the training topics** listed in the schedule below.  
2. **Discuss with your group** which sessions interest you individually and which ones may benefit the group as a whole.  
3. **Register early** — space is limited! Use the registration links provided for each training.  

Monthly emails will provide details and reminders for upcoming sessions, so you won’t miss a thing.

### Logistics

- **All sessions are held via Zoom.**  
- **Training slides and video recordings ** will be posted and available for download on this site.  

Let’s build stronger, smarter collaborations — together.

#### Schedule
<div style="font-size: 0.85em; overflow-x: auto;">
| **Workshop**                            | **Date & Time**                        | **Duration**        | **Registration**         |
|-----------------------------------------|----------------------------------------|---------------------|--------------------------|
| [Facilitating a Successful Working Group](s01_lecture_facilitating_working_group.qmd) | Aug 21, 2025<br>10am – 11am PT         | 60 min              | Register [here](https://ucsb.zoom.us/meeting/register/Eio-rXEeRPiyaBwPXX-z-Q)       |
| [Intro to Git and GitHub](s02_github_introduction.qmd)                 | Sep 10, 2025<br>10am – 11:30am PT      | 90 min              | Register [here](https://ucsb.zoom.us/meeting/register/5nnUZ9KTSj25ApzqKj-ZtQ)       |
| [Canva 101](s12_lecture_canvas.qmd)                               | Sep 24, 2025<br>10am – 11am PT         | 60 min              | Register [here](https://ucsb.zoom.us/meeting/register/sIjFUgMoSD2vC-P_aCnaiQ)       |
| [Data Management & Reproducibility](s03_lecture_data_mgmt_reproducibility.qmd)       | Oct 8, 2025<br>10am – 11am PT          | 60 min              | Register [here](https://ucsb.zoom.us/meeting/register/TGqzbDKiTQuGvFAMQsmW-Q)       |
| [Project Management on GitHub](s04_github_project_management.qmd)            | Nov 12, 2025<br>10am – 11am PT         | 60 min              | Register [here](https://ucsb.zoom.us/meeting/register/QtYCYvJlT1uJjnqyIMCCNw)       |
| [Collaborating with Git and GitHub](s05_github_collaboration.qmd)       | Dec 10, 2025<br>10am – 11:30am PT      | 90 min              | Register [here](https://ucsb.zoom.us/meeting/register/Vw2FO9BbRti2Mp_6TnZIlg)       |
| [Building a Communications Strategy](s06_lecture_communication_plan.qmd)         | Jan 21, 2026<br>10am – 11:30am PT      | 90 min              | Register [here](https://ucsb.zoom.us/meeting/register/df1DNFtATN-lwsADByDiiw)       |

</div>


## NCEAS Expertise

The [National Center for Ecological Analysis and Synthesis (NCEAS)](https://www.nceas.ucsb.edu/), a research affiliate of UCSB, is a global leader in ecological synthesis science, transforming how environmental research is conducted through data-driven collaboration. With over 30 years of success using this model among working groups and environmental professionals, NCEAS champions open science by developing tools and best practices for transparent, reproducible, and accessible research. It also invests heavily in training scientists, offering workshops and resources that build skills in data science, collaboration, and environmental analysis.


## Code of Conduct

By participating in this activity you agree to abide by the [NCEAS Code of Conduct](https://www.nceas.ucsb.edu/sites/default/files/2021-11/NCEAS_Code-of-Conduct_Nov2021_0.pdf).

## About this book

These written materials are the result of a continuous and collaborative effort at NCEAS to help researchers make their work more transparent and reproducible. This work began in the early 2000's, and reflects the expertise and diligence of many, many individuals. The primary authors are listed in the citation under each workshop material, with additional contributors recognized for their role in developing previous iterations of these or similar materials.

This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).

This is a Quarto book. To learn more about Quarto books visit <https://quarto.org/docs/books>.




