---
title: "One Pagers with Google Documents"
number-sections: false
---

<!---
Related GoogleSlide deck link: https://docs.google.com/presentation/d/1PWeFAZ0KFI84WmwJJIwzYSaWpg91Trbj-AQi1G2oQGI
--->

:::{.callout-tip icon="false"}
### {{< fa brain >}} Learning Objectives

After completing this session, you will be able to:

- Learn about free graphic resources like Coolers, Font Awesome, and the Noun Project 
- Reflect on your desired audience and goals for this science communication project
- Recognize compelling components of infographic content and layout
- Determine suitable color schemes for infographics and practice implementing them
- Customize infographics with text, fonts, photos, colors, and layouts in Google Docs

:::

<iframe width="560" height="380"src="https://docs.google.com/presentation/d/1PWeFAZ0KFI84WmwJJIwzYSaWpg91Trbj-AQi1G2oQGI/preview" allowfullscreen></iframe>

### Workshop Description

Graphical one-pagers are powerful ways to convey complex scientific information to a general audience and summarize working group outputs. Learn how to create compelling materials, including choices around fonts, layouts, content, and color schemes.

### Additional Resources

- [Ten Simple Rules for Better Figures](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833)
- Faces engage us: [photos with faces attract more likes and comments on Instagram](https://www.researchgate.net/publication/266655817_Faces_engage_us_photos_with_faces_attract_more_likes_and_comments_on_Instagram)
